### ISSUE TITLE
Inconsistant sensor values with Software Version 2.14

### ISSUE THREAD

**Issue by glucki99** [mampfes/ha_freeair_connect#12] opened 2024-07-13 14:42 UTC
The FreeAir Connect AddOn for HA seems not to work correctly for devices with the device sofware version 2.14.
The sensor values are unplausible and not consistant to the actual values, when connecting to freeair-connect.de via web browser.
Unfortunatly it is not possible to downgrade the FreeAir devices to software version 2.13 again.

**Comment by mampfes** [comment] 2024-07-13 15:31
Duplicate of #13

**Closed by mampfes** 2024-07-13 15:31 UTC
